# docker-compose.yml

version: '3.4'

services:
  mongo:
    image: mongo
    container_name: notebook_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notebook_web
    ports:
      - "5000:80"
    depends_on:
      - mongo

volumes:
  mongo-data:
